# Generated by Django 5.1.3 on 2024-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0003_cart_cartitems_customer_cart_customer_billcheckout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
